### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by itsmortoncornelius** [NeutrinosPlatform/scanlibrary#3]
Add a readme which explains how to use this library.

**Comment by ChrisTomAlx** [comment]
@itsmortoncornelius This is merely a fork that is being used for the cordova-plugin-document-scanner, Please view original libray [here](https://github.com/jhansireddy/AndroidScannerDemo). You can find all required documentation there.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by itsmortoncornelius** [comment]
ok, thanks
