### ISSUE TITLE
Applying filter infinite spinner

### ISSUE THREAD

**Issue by maverick-2013** [NeutrinosPlatform/scanlibrary#6]
Infinite spinner is showing after tapping any filters buttons simultaneously.

**Comment by ChrisTomAlx** [comment]
Fixed. Refer this [comment](https://github.com/NeutrinosPlatform/cordova-plugin-document-scanner/issues/74#issuecomment-724667450)

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
