### ISSUE TITLE
what changes has to be made while adding a new filter???

### ISSUE THREAD

**Issue by anshus7007** [NeutrinosPlatform/scanlibrary#8]

**Comment by ChrisTomAlx** [comment]
Refer to [ResultFragment.java](https://github.com/NeutrinosPlatform/scanlibrary/blob/master/library/src/main/java/com/scanlibrary/ResultFragment.java) and [result_layout.xml](https://github.com/NeutrinosPlatform/scanlibrary/blob/master/library/src/main/res/layout/result_layout.xml)

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
