### ISSUE TITLE
Android build issue

### ISSUE THREAD

**Issue by no0dles** [NeutrinosPlatform/scanlibrary#9]
Hey, we're using the cordova document scanner plugin which relies on your maven repository.

```
allprojects {
	repositories {
		maven { 
			url 'https://jitpack.io' 
		}
	}
}

dependencies {
	implementation 'com.github.NeutrinosPlatform:scanlibrary:2.5'
}
```

Somehow the 2.5 version is not available anymore, is it possible to republish this? 

Thanks in advance!

**Comment by ChrisTomAlx** [comment]
Published a new verison ( [4.2.7](https://www.npmjs.com/package/cordova-plugin-document-scanner) ) of the document scanner with a new scanlibrary build... Should be fine now.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
